language: node_js
node_js:
- lts/*
before_script:
- npm ci
- npm run build
script:
- npm run lint
- npm run test
after_success:
- pkg package.json --targets node12-win-x64,node12-linux-x64,node12-macos-x64 --out-path executable

deploy:
  - provider: npm
    email: "$NPM_MAIL"
    api_key: "$NPM_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      repo: ShowComposer/manager
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "executable/*"
    skip_cleanup: true
    on:
      tags: true
